id: A4940DAFF
title: SÄdhana of the Great Master Vairotsana
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 02:00:51.047637
  last_modified_at: 2022-03-01 02:00:51.047643
